GNU nano 8.2         .github/workflows/build-container.yml
name: Build and Push Container
on:
  push:
    branches:
      - workinprogress

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.mjaysaad }}
          password: ${{ secrets.Abdulmajed@79 }}

